name: "Build on Linux/macOS"

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - chore/*
    tags:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  BORING_SSL_COMMIT: 673e61fc215b178a90c0e67858bbf162c8158993
  MACOSX_DEPLOYMENT_TARGET: 11.0

jobs:
  build:
    name: (${{ matrix.host }}) Build curl-impersonate
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            host: x86_64-linux-gnu
            zigflags: -target x86_64-linux-gnu.2.17
            make: make
          - os: ubuntu-latest
            arch: x86_64
            host: x86_64-linux-musl
            zigflags: -target x86_64-linux-musl -fPIC
            make: make
          - os: ubuntu-latest
            arch: i386
            host: i386-linux-gnu
            zigflags: -target x86-linux-gnu.2.17
            make: make
          - os: ubuntu-latest
            arch: aarch64
            host: aarch64-linux-gnu
            zigflags: -target aarch64-linux-gnu.2.17
            make: make
          - os: ubuntu-latest
            arch: aarch64
            host: aarch64-linux-musl
            zigflags: -target aarch64-linux-musl -fPIC -mno-outline-atomics
            make: make
          - os: ubuntu-latest
            arch: arm
            host: arm-linux-gnueabihf
            zigflags: -target arm-linux-gnueabihf.2.17 -mcpu=arm1176jzf_s
            make: make
          - os: ubuntu-latest
            arch: riscv64
            host: riscv64-linux-gnu
            zigflags: -target riscv64-linux-gnu.2.27
            make: make
          - os: macos-15-intel
            arch: x86_64
            host: x86_64-macos
            make: gmake
          - os: macos-14
            arch: arm64
            host: arm64-macos
            make: gmake
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up zig
        if: runner.os == 'Linux'
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Set zig env
        if: runner.os == 'Linux'
        run: |
          echo "CC=${{ github.workspace }}/zigshim/cc" >> $GITHUB_ENV
          echo "CXX=${{ github.workspace }}/zigshim/cxx" >> $GITHUB_ENV
          echo "AR=${{ github.workspace }}/zigshim/ar" >> $GITHUB_ENV
          echo "ZIG_FLAGS=${{ matrix.zigflags }}" >> $GITHUB_ENV

      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential pkg-config cmake ninja-build curl autoconf automake libtool
          sudo apt-get install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-riscv64-linux-gnu
          sudo apt-get install golang-go

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config make cmake ninja autoconf automake libtool gpatch
          # Chrome version dependencies, install only not installed.
          which go || brew install go
          # Dependencies for the tests
          brew install tcpdump curl nghttp2

      - name: Run configure script
        run: |
          set -e
          mkdir ${{ runner.temp }}/install
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            ./configure --prefix=${{ runner.temp }}/install --enable-static --disable-shared \
                        --host=${{ matrix.host }} \
                        --with-ca-path=/etc/ssl/certs \
                        --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
          else
            ./configure --prefix=${{ runner.temp }}/install --enable-static --disable-shared
          fi

      - name: Build statically
        run: |
          set -e
          ${{ matrix.make }} build
          ${{ matrix.make }} checkbuild
          if [[ "${{ runner.os }}" == "Linux" && "${{ endsWith(matrix.host, 'musl') }}" == "true" ]]; then
            ${{ matrix.make }} install
          else
            ${{ matrix.make }} install-strip
          fi

      - name: Create tar release files
        run: |
          cp zlib-*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          cp zstd-*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          cp nghttp2*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          cp nghttp3*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          cp ngtcp2*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          cp brotli*/out/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          cp boringssl*/lib/lib*.a ${{ runner.temp }}/install/lib
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            cp libidn2*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
            cp libunistring*/installed/lib/lib*.a ${{ runner.temp }}/install/lib
          fi

          cd ${{ runner.temp }}/install/lib
          ls -lah .
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            tar -c -z -f ${{ runner.temp }}/libcurl-impersonate-${{ github.ref_name }}.${{ matrix.host }}.tar.gz lib*
          else
            tar -c -z -f ${{ runner.temp }}/libcurl-impersonate.${{ matrix.host }}.tar.gz lib*
          fi
          echo "release_file_lib=${{ runner.temp }}/libcurl-impersonate-${{ github.ref_name }}.${{ matrix.host }}.tar.gz" >> $GITHUB_ENV

          cd ${{ runner.temp }}/install/bin
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            tar -c -z -f ${{ runner.temp }}/curl-impersonate-${{ github.ref_name }}.${{ matrix.host }}.tar.gz curl-impersonate curl_*
          else
            tar -c -z -f ${{ runner.temp }}/curl-impersonate.${{ matrix.host }}.tar.gz curl-impersonate curl_*
          fi
          echo "release_file_bin=${{ runner.temp }}/curl-impersonate-${{ github.ref_name }}.${{ matrix.host }}.tar.gz" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts.${{ matrix.host }}
          path: |
            ${{ runner.temp }}/libcurl-impersonate*.tar.gz
            ${{ runner.temp }}/curl-impersonate*.tar.gz

      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
              ${{ env.release_file_lib }}
              ${{ env.release_file_bin }}
